#! /usr/bin/bash
#SBATCH --job-name=pipeline
#SBATCH --partition=gpu
#SBATCH --mail-type=ALL
#SBATCH --mail-user=aelhussein@nygenome.org
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=40G
#SBATCH --gres gpu:tesla
#SBATCH --time=45:00:00

source ~/anaconda3/bin/activate ~/anaconda3/envs/cuda_env/
conda activate cuda_env
module load cuda

DIR='/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl'
python $DIR/code/pipeline.py --datasets=Heart,FMNIST,EMNIST,Sentiment,mimic,CIFAR,ISIC
#python $DIR/code/pipeline.py --datasets=ISIC --cross_device
