#! /usr/bin/bash
#SBATCH --job-name=metrics   
#SBATCH --partition=gpu
#SBATCH --mail-type=ALL
#SBATCH --mail-user=aelhussein@nygenome.org
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=60G
#SBATCH --gres gpu:tesla
#SBATCH --time=40:00:00

source ~/anaconda3/bin/activate ~/anaconda3/envs/cuda_env/
conda activate cuda_env
module load cuda

DIR='/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl'
#python $DIR/code/layer_pfl_metrics.py --datasets=Heart,FMNIST,EMNIST,Sentiment,mimic,CIFAR,ISIC

python $DIR/code/layer_pfl_metrics.py --datasets=Sentiment,mimic,CIFAR,ISIC --federated