#!/usr/bin/bash
#SBATCH --job-name=metrics   
#SBATCH --partition=gpu
#SBATCH --mail-type=ALL
#SBATCH --mail-user=aelhussein@nygenome.org
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=60G
#SBATCH --gres gpu:tesla
#SBATCH --time=40:00:00

source ~/anaconda3/bin/activate ~/anaconda3/envs/cuda_env/
conda activate cuda_env
module load cuda

# Default values
DEFAULT_DIR='/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl'
DEFAULT_DATASETS='Heart,FMNIST,EMNIST,Sentiment,mimic,CIFAR,ISIC'
DEFAULT_FED='false'  # Use string 'false' instead of False

DIR=${1:-$DEFAULT_DIR}
DATASETS=${2:-$DEFAULT_DATASETS}
FED=${3:-$DEFAULT_FED}

echo "Using directory: $DIR"
echo "Using datasets: $DATASETS"
echo "Federated mode: $FED"

python $DIR/code/layer_pfl_metrics.py --datasets=$DATASETS --federated=$FED